const books = [
    {
        title: "Clean Code",
        author: "Robert C. Martin",
        description: "A handbook of agile software craftsmanship that teaches programmers how to write clean, readable, and maintainable code.",
        category: "Programming",
        publisher: "Prentice Hall",
        publishedYear: 2008,
        totalCopies: 10,
        availableCopies: 10,
        ratings: 4.7,
        isbn: "978-0132350884",
        coverImage: "http://localhost:5000/assets/books/book1.jpg"
    },
    {
        title: "Atomic Habits",
        author: "James Clear",
        description: "An easy and proven way to build good habits and break bad ones through tiny changes that deliver remarkable results.",
        category: "Self Help",
        publisher: "Avery",
        publishedYear: 2018,
        totalCopies: 8,
        availableCopies: 8,
        ratings: 4.8,
        isbn: "978-0735211292",
        coverImage: "http://localhost:5000/assets/books/book2.jpg"
    },
    {
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt & David Thomas",
        description: "A classic guide covering coding best practices, career tips, and craftsmanship for modern software developers.",
        category: "Programming",
        publisher: "Addison-Wesley",
        publishedYear: 1999,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.6,
        isbn: "978-0135957059",
        coverImage: "http://localhost:5000/assets/books/book3.jpg"
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A vivid portrait of the Jazz Age, exploring themes of wealth, class, love, and the American Dream through the eyes of narrator Nick Carraway.",
        category: "Fiction",
        publisher: "Scribner",
        publishedYear: 1925,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.3,
        isbn: "978-0743273565",
        coverImage: "http://localhost:5000/assets/books/book4.jpg"
    },
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "A gripping tale of racial injustice and moral growth set in the American South, narrated by the young Scout Finch.",
        category: "Fiction",
        publisher: "J. B. Lippincott & Co.",
        publishedYear: 1960,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.8,
        isbn: "978-0061935466",
        coverImage: "http://localhost:5000/assets/books/book5.jpg"
    },
    {
        title: "1984",
        author: "George Orwell",
        description: "A dystopian novel about a totalitarian society where Big Brother watches your every move and independent thought is a crime.",
        category: "Dystopian",
        publisher: "Secker & Warburg",
        publishedYear: 1949,
        totalCopies: 9,
        availableCopies: 9,
        ratings: 4.7,
        isbn: "978-0451524935",
        coverImage: "http://localhost:5000/assets/books/book6.jpg"
    },
    {
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        description: "The first book in the beloved Harry Potter series, following a young boy who discovers he is a wizard and begins his education at Hogwarts.",
        category: "Fantasy",
        publisher: "Scholastic",
        publishedYear: 1997,
        totalCopies: 12,
        availableCopies: 12,
        ratings: 4.9,
        isbn: "978-0590353427",
        coverImage: "http://localhost:5000/assets/books/book7.jpg"
    },
    {
        title: "The Alchemist",
        author: "Paulo Coelho",
        description: "An inspiring allegorical novel about following your dreams and listening to your heart, following a young shepherd's journey to find treasure.",
        category: "Fiction",
        publisher: "HarperOne",
        publishedYear: 1988,
        totalCopies: 8,
        availableCopies: 8,
        ratings: 4.6,
        isbn: "978-0062315007",
        coverImage: "http://localhost:5000/assets/books/book8.jpg"
    },
    {
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        description: "A sweeping narrative of humanity's creation and evolution, exploring how biology and history have defined us.",
        category: "History",
        publisher: "Harper",
        publishedYear: 2011,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.7,
        isbn: "978-0062316097",
        coverImage: "http://localhost:5000/assets/books/book9.jpg"
    },
    {
        title: "The Design of Everyday Things",
        author: "Don Norman",
        description: "A powerful primer on how—and why—some products satisfy customers while others frustrate them, focused on user-centered design.",
        category: "Design",
        publisher: "Basic Books",
        publishedYear: 1988,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.5,
        isbn: "978-0465050659",
        coverImage: "http://localhost:5000/assets/books/book10.jpg"
    },
    {
        title: "Deep Work",
        author: "Cal Newport",
        description: "Rules for focused success in a distracted world, arguing that the ability to focus without distraction is a superpower in our economy.",
        category: "Self Help",
        publisher: "Grand Central Publishing",
        publishedYear: 2016,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.6,
        isbn: "978-1455586691",
        coverImage: "http://localhost:5000/assets/books/book11.jpg"
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        description: "An epic science fiction saga set in a distant future feudal interstellar society where noble houses control planetary fiefs.",
        category: "Science Fiction",
        publisher: "Chilton Books",
        publishedYear: 1965,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.7,
        isbn: "978-0441013593",
        coverImage: "http://localhost:5000/assets/books/book12.jpg"
    },
    {
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        description: "Powerful lessons in personal change providing a principle-centered approach for solving personal and professional problems.",
        category: "Self Help",
        publisher: "Free Press",
        publishedYear: 1989,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.5,
        isbn: "978-1982137274",
        coverImage: "http://localhost:5000/assets/books/book13.jpg"
    },
    {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        description: "A timeless classic on the power of personal beliefs and the role they play in achieving success.",
        category: "Self Help",
        publisher: "The Ralston Society",
        publishedYear: 1937,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.4,
        isbn: "978-1585424331",
        coverImage: "http://localhost:5000/assets/books/book14.jpg"
    },
    {
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        description: "A comedic science fiction series following Arthur Dent as he travels through space after Earth is demolished to make way for a hyperspace bypass.",
        category: "Science Fiction",
        publisher: "Pan Books",
        publishedYear: 1979,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.7,
        isbn: "978-0345391803",
        coverImage: "http://localhost:5000/assets/books/book15.jpg"
    },
    {
        title: "You Don't Know JS",
        author: "Kyle Simpson",
        description: "A deep dive into the core mechanisms of the JavaScript language, clearing up misconceptions and building a solid foundation.",
        category: "Programming",
        publisher: "O'Reilly Media",
        publishedYear: 2014,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.8,
        isbn: "978-1491924464",
        coverImage: "http://localhost:5000/assets/books/book16.jpg"
    },
    {
        title: "The Lean Startup",
        author: "Eric Ries",
        description: "A new approach for continuous innovation that teaches how to drive a startup—and apply the principles of lean manufacturing to innovation.",
        category: "Business",
        publisher: "Crown Business",
        publishedYear: 2011,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.5,
        isbn: "978-0307887894",
        coverImage: "http://localhost:5000/assets/books/book17.jpg"
    },
    {
        title: "Brave New World",
        author: "Aldous Huxley",
        description: "A dystopian novel set in a futuristic world state where citizens are environmentally engineered into a passive, consumerist society.",
        category: "Dystopian",
        publisher: "Chatto & Windus",
        publishedYear: 1932,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.4,
        isbn: "978-0060850524",
        coverImage: "http://localhost:5000/assets/books/book18.jpg"
    },
    {
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        description: "An epic high-fantasy novel that follows the hobbit Frodo Baggins as he and his companions embark on a quest to destroy the One Ring.",
        category: "Fantasy",
        publisher: "George Allen & Unwin",
        publishedYear: 1954,
        totalCopies: 8,
        availableCopies: 8,
        ratings: 4.9,
        isbn: "978-0544003415",
        coverImage: "http://localhost:5000/assets/books/book19.jpg"
    },
    {
        title: "Zero to One",
        author: "Peter Thiel",
        description: "Notes on startups, or how to build the future—how to build companies that create new things rather than copying what already exists.",
        category: "Business",
        publisher: "Crown Business",
        publishedYear: 2014,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.5,
        isbn: "978-0804139021",
        coverImage: "http://localhost:5000/assets/books/book20.jpg"
    },
    {
        title: "The Power of Now",
        author: "Eckhart Tolle",
        description: "A guide to spiritual enlightenment emphasizing the importance of living in the present moment and avoiding past or future thoughts.",
        category: "Self Help",
        publisher: "New World Library",
        publishedYear: 1997,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.4,
        isbn: "978-1577314806",
        coverImage: "http://localhost:5000/assets/books/book21.jpg"
    },
    {
        title: "Introduction to Algorithms",
        author: "Thomas H. Cormen",
        description: "A comprehensive textbook on algorithms, widely used in computer science courses worldwide for its depth and clarity.",
        category: "Programming",
        publisher: "MIT Press",
        publishedYear: 1990,
        totalCopies: 4,
        availableCopies: 4,
        ratings: 4.6,
        isbn: "978-0262033848",
        coverImage: "http://localhost:5000/assets/books/book22.jpg"
    },
    {
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        description: "What the rich teach their kids about money that the poor and middle class do not—a personal finance classic.",
        category: "Finance",
        publisher: "Warner Books",
        publishedYear: 1997,
        totalCopies: 8,
        availableCopies: 8,
        ratings: 4.4,
        isbn: "978-1612680194",
        coverImage: "http://localhost:5000/assets/books/book23.jpg"
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A story of teenage alienation and loss of innocence, following Holden Caulfield over a few days in New York City.",
        category: "Fiction",
        publisher: "Little, Brown and Company",
        publishedYear: 1951,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.2,
        isbn: "978-0316769174",
        coverImage: "http://localhost:5000/assets/books/book24.jpg"
    },
    {
        title: "Don't Make Me Think",
        author: "Steve Krug",
        description: "A common sense approach to web usability that has become one of the most influential books in UX/web design.",
        category: "Design",
        publisher: "New Riders",
        publishedYear: 2000,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.5,
        isbn: "978-0321965516",
        coverImage: "http://localhost:5000/assets/books/book25.jpg"
    },
    {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        description: "An exploration of the two systems that drive the way we think—fast, intuitive thinking and slow, deliberate thinking.",
        category: "Psychology",
        publisher: "Farrar, Straus and Giroux",
        publishedYear: 2011,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.6,
        isbn: "978-0374533557",
        coverImage: "http://localhost:5000/assets/books/book26.jpg"
    },
    {
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        description: "A counterintuitive approach to living a good life by focusing on what truly matters and letting go of what doesn't.",
        category: "Self Help",
        publisher: "HarperOne",
        publishedYear: 2016,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.3,
        isbn: "978-0062457714",
        coverImage: "http://localhost:5000/assets/books/book27.jpg"
    },
    {
        title: "Good to Great",
        author: "Jim Collins",
        description: "Why some companies make the leap from good to great—and why most don't. Based on research into what separates great companies from merely good ones.",
        category: "Business",
        publisher: "HarperBusiness",
        publishedYear: 2001,
        totalCopies: 5,
        availableCopies: 5,
        ratings: 4.5,
        isbn: "978-0066620992",
        coverImage: "http://localhost:5000/assets/books/book28.jpg"
    },
    {
        title: "The Art of War",
        author: "Sun Tzu",
        description: "An ancient Chinese military treatise dating from the 5th century BC that has been applied to business, law, and sports strategy.",
        category: "History",
        publisher: "Oxford University Press",
        publishedYear: -500,
        totalCopies: 9,
        availableCopies: 9,
        ratings: 4.5,
        isbn: "978-1599869773",
        coverImage: "http://localhost:5000/assets/books/book29.jpg"
    },
    {
        title: "Cracking the Coding Interview",
        author: "Gayle Laakmann McDowell",
        description: "189 programming questions and solutions to help you prepare for technical interviews at top tech companies.",
        category: "Programming",
        publisher: "CareerCup",
        publishedYear: 2008,
        totalCopies: 6,
        availableCopies: 6,
        ratings: 4.7,
        isbn: "978-0984782857",
        coverImage: "http://localhost:5000/assets/books/book30.jpg"
    },
    {
        title: "Meditations",
        author: "Marcus Aurelius",
        description: "Personal writings of the Roman Emperor Marcus Aurelius, recording his private notes to himself and ideas on Stoic philosophy.",
        category: "Philosophy",
        publisher: "Penguin Classics",
        publishedYear: 180,
        totalCopies: 7,
        availableCopies: 7,
        ratings: 4.8,
        isbn: "978-0140449334",
        coverImage: "http://localhost:5000/assets/books/book31.jpg"
    }
];

export default books;
